"""Tests for the envoy.parser module."""

import os
import pytest

from envoy.parser import parse_env_file, write_env_file


@pytest.fixture
def tmp_env_file(tmp_path):
    """Return a helper that writes content to a temp .env file."""
    def _write(content: str) -> str:
        p = tmp_path / ".env"
        p.write_text(content, encoding="utf-8")
        return str(p)
    return _write


def test_parse_simple_key_value(tmp_env_file):
    path = tmp_env_file("APP_ENV=production\nDEBUG=false\n")
    result = parse_env_file(path)
    assert result == {"APP_ENV": "production", "DEBUG": "false"}


def test_parse_ignores_comments_and_blank_lines(tmp_env_file):
    content = "# This is a comment\n\nDB_HOST=localhost\n"
    path = tmp_env_file(content)
    result = parse_env_file(path)
    assert result == {"DB_HOST": "localhost"}


def test_parse_strips_double_quotes(tmp_env_file):
    path = tmp_env_file('SECRET_KEY="my secret value"\n')
    result = parse_env_file(path)
    assert result == {"SECRET_KEY": "my secret value"}


def test_parse_strips_single_quotes(tmp_env_file):
    path = tmp_env_file("API_URL='https://example.com'\n")
    result = parse_env_file(path)
    assert result == {"API_URL": "https://example.com"}


def test_parse_raises_for_missing_file():
    with pytest.raises(FileNotFoundError, match="Env file not found"):
        parse_env_file("/nonexistent/path/.env")


def test_parse_raises_for_invalid_line(tmp_env_file):
    path = tmp_env_file("THIS IS INVALID\n")
    with pytest.raises(ValueError, match="Invalid syntax"):
        parse_env_file(path)


def test_write_and_read_roundtrip(tmp_path):
    env_vars = {"PORT": "8080", "HOST": "0.0.0.0", "NAME": "my app"}
    filepath = str(tmp_path / ".env")

    write_env_file(filepath, env_vars, comment="Generated by envoy-cli")
    assert os.path.exists(filepath)

    result = parse_env_file(filepath)
    assert result == env_vars


def test_write_includes_header_comment(tmp_path):
    filepath = str(tmp_path / ".env")
    write_env_file(filepath, {"X": "1"}, comment="auto-generated")

    raw = open(filepath).read()
    assert "# auto-generated" in raw


def test_write_quotes_values_with_spaces(tmp_path):
    filepath = str(tmp_path / ".env")
    write_env_file(filepath, {"GREETING": "hello world"})

    raw = open(filepath).read()
    assert 'GREETING="hello world"' in raw
